package e2e

import (
	"bytes"
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/starquill/URL-Shortening-Service/internal/cache"
	"github.com/starquill/URL-Shortening-Service/internal/config"
	"github.com/starquill/URL-Shortening-Service/internal/database"
	"github.com/starquill/URL-Shortening-Service/internal/generator"
	"github.com/starquill/URL-Shortening-Service/internal/handler"
	"github.com/starquill/URL-Shortening-Service/internal/store"
)

var (
	testRouter     *chi.Mux
	testURLStore   *store.URLStore
	testCache      *cache.RedisCache
	testGenerator  *generator.ShortCodeGenerator
	testURLHandler *handler.URLHandler
)

func setupE2E(t *testing.T) {
	t.Helper()

	// Change to project root directory for config loading
	projectRoot, err := filepath.Abs("../..")
	if err != nil {
		t.Fatalf("Failed to get project root: %v", err)
	}

	originalDir, _ := os.Getwd()
	os.Chdir(projectRoot)
	defer os.Chdir(originalDir)

	// Load config
	cfg, err := config.Load()
	if err != nil {
		t.Fatalf("Failed to load config: %v", err)
	}

	ctx := context.Background()

	// Setup database
	pool, err := database.NewPool(ctx, cfg.Database.URL)
	if err != nil {
		t.Fatalf("Failed to connect to database: %v", err)
	}

	// Run migrations
	if err := database.RunMigrations(cfg.Database.URL); err != nil {
		t.Fatalf("Failed to run migrations: %v", err)
	}

	// Setup Redis
	ttl, _ := time.ParseDuration(cfg.Redis.TTL)
	testCache, err = cache.NewRedisCache(cfg.Redis.URL, "", 0, ttl)
	if err != nil {
		t.Fatalf("Failed to connect to Redis: %v", err)
	}

	// Initialize components
	testURLStore = store.NewURLStore(pool)
	testGenerator = generator.NewShortCodeGenerator(testURLStore, 7)
	testURLHandler = handler.NewURLHandler(testURLStore, testCache, testGenerator, cfg.Server.BaseURL)

	// Setup router
	testRouter = chi.NewRouter()
	testRouter.Get("/health", handler.Health)
	testRouter.Get("/{code}", testURLHandler.RedirectURL)
	testRouter.Post("/shorten", testURLHandler.CreateShortURL)
	testRouter.Route("/api/urls/{code}", func(r chi.Router) {
		r.Get("/", testURLHandler.GetURL)
		r.Put("/", testURLHandler.UpdateURL)
		r.Delete("/", testURLHandler.DeleteURL)
	})
}

func teardownE2E(t *testing.T) {
	t.Helper()
	// Clean up test data
	// Note: In a real scenario, you might want to use a separate test database
	// or clean up specific test records
	if testCache != nil {
		testCache.Close()
	}
}

func TestE2E_HealthCheck(t *testing.T) {
	setupE2E(t)
	defer teardownE2E(t)

	req := httptest.NewRequest(http.MethodGet, "/health", nil)
	w := httptest.NewRecorder()

	testRouter.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("Expected status 200, got %d", w.Code)
	}

	var response map[string]string
	json.NewDecoder(w.Body).Decode(&response)

	if response["status"] != "ok" {
		t.Errorf("Expected status 'ok', got '%s'", response["status"])
	}
}

func TestE2E_CreateShortURL_AutoGenerated(t *testing.T) {
	setupE2E(t)
	defer teardownE2E(t)

	payload := map[string]string{
		"url": "https://www.example.com",
	}
	body, _ := json.Marshal(payload)

	req := httptest.NewRequest(http.MethodPost, "/shorten", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	testRouter.ServeHTTP(w, req)

	if w.Code != http.StatusCreated {
		t.Fatalf("Expected status 201, got %d. Body: %s", w.Code, w.Body.String())
	}

	var response map[string]string
	json.NewDecoder(w.Body).Decode(&response)

	if response["short_code"] == "" {
		t.Error("Expected short_code to be generated")
	}

	if response["original_url"] != "https://www.example.com" {
		t.Errorf("Expected original_url 'https://www.example.com', got '%s'", response["original_url"])
	}

	if len(response["short_code"]) != 7 {
		t.Errorf("Expected short_code length 7, got %d", len(response["short_code"]))
	}
}

func TestE2E_CreateShortURL_CustomCode(t *testing.T) {
	setupE2E(t)
	defer teardownE2E(t)

	customCode := "e2e" + time.Now().Format("0405")

	payload := map[string]string{
		"url":         "https://www.github.com",
		"custom_code": customCode,
	}
	body, _ := json.Marshal(payload)

	req := httptest.NewRequest(http.MethodPost, "/shorten", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	testRouter.ServeHTTP(w, req)

	if w.Code != http.StatusCreated {
		t.Fatalf("Expected status 201, got %d. Body: %s", w.Code, w.Body.String())
	}

	var response map[string]string
	json.NewDecoder(w.Body).Decode(&response)

	if response["short_code"] != customCode {
		t.Errorf("Expected short_code '%s', got '%s'", customCode, response["short_code"])
	}

	// Cleanup
	defer func() {
		testURLStore.Delete(context.Background(), customCode)
	}()
}

func TestE2E_CreateShortURL_InvalidURL(t *testing.T) {
	setupE2E(t)
	defer teardownE2E(t)

	payload := map[string]string{
		"url": "not-a-valid-url",
	}
	body, _ := json.Marshal(payload)

	req := httptest.NewRequest(http.MethodPost, "/shorten", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	testRouter.ServeHTTP(w, req)

	if w.Code != http.StatusBadRequest {
		t.Errorf("Expected status 400, got %d", w.Code)
	}

	var response map[string]string
	json.NewDecoder(w.Body).Decode(&response)

	if response["error"] == "" {
		t.Error("Expected error message")
	}
}

func TestE2E_CreateShortURL_CustomCodeTooShort(t *testing.T) {
	setupE2E(t)
	defer teardownE2E(t)

	payload := map[string]string{
		"url":         "https://www.example.com",
		"custom_code": "ab",
	}
	body, _ := json.Marshal(payload)

	req := httptest.NewRequest(http.MethodPost, "/shorten", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	testRouter.ServeHTTP(w, req)

	if w.Code != http.StatusBadRequest {
		t.Errorf("Expected status 400, got %d", w.Code)
	}

	var response map[string]string
	json.NewDecoder(w.Body).Decode(&response)

	if response["error"] != "short code must be at least 3 characters long" {
		t.Errorf("Unexpected error message: %s", response["error"])
	}
}

func TestE2E_CreateShortURL_DuplicateCustomCode(t *testing.T) {
	setupE2E(t)
	defer teardownE2E(t)

	customCode := "dup" + time.Now().Format("0405")

	// Create first URL
	payload := map[string]string{
		"url":         "https://www.example.com",
		"custom_code": customCode,
	}
	body, _ := json.Marshal(payload)

	req := httptest.NewRequest(http.MethodPost, "/shorten", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	testRouter.ServeHTTP(w, req)

	if w.Code != http.StatusCreated {
		t.Fatalf("Expected status 201, got %d", w.Code)
	}

	// Try to create duplicate
	req2 := httptest.NewRequest(http.MethodPost, "/shorten", bytes.NewReader(body))
	req2.Header.Set("Content-Type", "application/json")
	w2 := httptest.NewRecorder()

	testRouter.ServeHTTP(w2, req2)

	if w2.Code != http.StatusConflict {
		t.Errorf("Expected status 409, got %d", w2.Code)
	}

	var response map[string]string
	json.NewDecoder(w2.Body).Decode(&response)

	if response["error"] != "custom code already exists" {
		t.Errorf("Unexpected error message: %s", response["error"])
	}

	// Cleanup
	defer func() {
		testURLStore.Delete(context.Background(), customCode)
	}()
}

func TestE2E_RedirectURL(t *testing.T) {
	setupE2E(t)
	defer teardownE2E(t)

	customCode := "rdr" + time.Now().Format("0405")
	expectedURL := "https://www.redirect-test.com"

	// Create URL first
	ctx := context.Background()
	_, err := testURLStore.Create(ctx, expectedURL, customCode)
	if err != nil {
		t.Fatalf("Failed to create test URL: %v", err)
	}

	// Test redirect
	req := httptest.NewRequest(http.MethodGet, "/"+customCode, nil)
	w := httptest.NewRecorder()

	testRouter.ServeHTTP(w, req)

	if w.Code != http.StatusFound {
		t.Errorf("Expected status 302, got %d", w.Code)
	}

	location := w.Header().Get("Location")
	if location != expectedURL {
		t.Errorf("Expected redirect to '%s', got '%s'", expectedURL, location)
	}

	// Verify access count incremented (give async operation time to complete)
	time.Sleep(100 * time.Millisecond)
	urlRecord, _ := testURLStore.GetByShortCode(ctx, customCode)
	if urlRecord.AccessCount < 1 {
		t.Errorf("Expected access_count >= 1, got %d", urlRecord.AccessCount)
	}

	// Cleanup
	defer func() {
		testURLStore.Delete(ctx, customCode)
	}()
}

func TestE2E_GetURL(t *testing.T) {
	setupE2E(t)
	defer teardownE2E(t)

	customCode := "get" + time.Now().Format("0405")
	expectedURL := "https://www.geturl-test.com"

	// Create URL first
	ctx := context.Background()
	_, err := testURLStore.Create(ctx, expectedURL, customCode)
	if err != nil {
		t.Fatalf("Failed to create test URL: %v", err)
	}

	// Get URL
	req := httptest.NewRequest(http.MethodGet, "/api/urls/"+customCode, nil)
	w := httptest.NewRecorder()

	testRouter.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("Expected status 200, got %d", w.Code)
	}

	var response map[string]interface{}
	json.NewDecoder(w.Body).Decode(&response)

	if response["url"] != expectedURL {
		t.Errorf("Expected url '%s', got '%s'", expectedURL, response["url"])
	}

	if response["short_code"] != customCode {
		t.Errorf("Expected short_code '%s', got '%s'", customCode, response["short_code"])
	}

	// Cleanup
	defer func() {
		testURLStore.Delete(ctx, customCode)
	}()
}

func TestE2E_UpdateURL(t *testing.T) {
	setupE2E(t)
	defer teardownE2E(t)

	customCode := "upd" + time.Now().Format("0405")
	originalURL := "https://www.original.com"
	newURL := "https://www.updated.com"

	// Create URL first
	ctx := context.Background()
	_, err := testURLStore.Create(ctx, originalURL, customCode)
	if err != nil {
		t.Fatalf("Failed to create test URL: %v", err)
	}

	// Update URL
	payload := map[string]string{
		"url": newURL,
	}
	body, _ := json.Marshal(payload)

	req := httptest.NewRequest(http.MethodPut, "/api/urls/"+customCode, bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	testRouter.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("Expected status 200, got %d", w.Code)
	}

	var response map[string]interface{}
	json.NewDecoder(w.Body).Decode(&response)

	if response["url"] != newURL {
		t.Errorf("Expected url '%s', got '%s'", newURL, response["url"])
	}

	// Verify in database
	urlRecord, _ := testURLStore.GetByShortCode(ctx, customCode)
	if urlRecord.URL != newURL {
		t.Errorf("Expected URL in DB to be '%s', got '%s'", newURL, urlRecord.URL)
	}

	// Cleanup
	defer func() {
		testURLStore.Delete(ctx, customCode)
	}()
}

func TestE2E_DeleteURL(t *testing.T) {
	setupE2E(t)
	defer teardownE2E(t)

	customCode := "del" + time.Now().Format("0405")
	testURL := "https://www.delete-test.com"

	// Create URL first
	ctx := context.Background()
	_, err := testURLStore.Create(ctx, testURL, customCode)
	if err != nil {
		t.Fatalf("Failed to create test URL: %v", err)
	}

	// Delete URL
	req := httptest.NewRequest(http.MethodDelete, "/api/urls/"+customCode, nil)
	w := httptest.NewRecorder()

	testRouter.ServeHTTP(w, req)

	if w.Code != http.StatusNoContent {
		t.Errorf("Expected status 204, got %d", w.Code)
	}

	// Verify deletion
	_, err = testURLStore.GetByShortCode(ctx, customCode)
	if err == nil {
		t.Error("Expected URL to be deleted, but it still exists")
	}
}

func TestE2E_GetURL_NotFound(t *testing.T) {
	setupE2E(t)
	defer teardownE2E(t)

	req := httptest.NewRequest(http.MethodGet, "/api/urls/nonexistent", nil)
	w := httptest.NewRecorder()

	testRouter.ServeHTTP(w, req)

	if w.Code != http.StatusNotFound {
		t.Errorf("Expected status 404, got %d", w.Code)
	}

	var response map[string]string
	json.NewDecoder(w.Body).Decode(&response)

	if response["error"] == "" {
		t.Error("Expected error message")
	}
}

func TestE2E_CacheInvalidation(t *testing.T) {
	setupE2E(t)
	defer teardownE2E(t)

	customCode := "cch" + time.Now().Format("0405")
	originalURL := "https://www.cache-original.com"
	newURL := "https://www.cache-updated.com"

	ctx := context.Background()

	// Create URL
	_, err := testURLStore.Create(ctx, originalURL, customCode)
	if err != nil {
		t.Fatalf("Failed to create test URL: %v", err)
	}

	// Populate cache via redirect
	req1 := httptest.NewRequest(http.MethodGet, "/"+customCode, nil)
	w1 := httptest.NewRecorder()
	testRouter.ServeHTTP(w1, req1)

	// Verify cache has original URL
	cachedURL, err := testCache.Get(ctx, customCode)
	if err != nil || cachedURL != originalURL {
		t.Errorf("Expected cache to have '%s', got '%s' (error: %v)", originalURL, cachedURL, err)
	}

	// Update URL (should invalidate cache)
	payload := map[string]string{"url": newURL}
	body, _ := json.Marshal(payload)
	req2 := httptest.NewRequest(http.MethodPut, "/api/urls/"+customCode, bytes.NewReader(body))
	req2.Header.Set("Content-Type", "application/json")
	w2 := httptest.NewRecorder()
	testRouter.ServeHTTP(w2, req2)

	// Verify cache was invalidated
	_, err = testCache.Get(ctx, customCode)
	if err == nil {
		t.Error("Expected cache to be invalidated after update")
	}

	// Redirect again (should populate cache with new URL)
	req3 := httptest.NewRequest(http.MethodGet, "/"+customCode, nil)
	w3 := httptest.NewRecorder()
	testRouter.ServeHTTP(w3, req3)

	// Verify redirect goes to new URL
	location := w3.Header().Get("Location")
	if location != newURL {
		t.Errorf("Expected redirect to '%s', got '%s'", newURL, location)
	}

	// Cleanup
	defer func() {
		testURLStore.Delete(ctx, customCode)
	}()
}
